modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
	modId="customstartinggear"
	displayName="Custom Starter Gear"
    version="2.0.3"
	authors="brandon3055"
	description=''''''

[[dependencies.customstartinggear]]
    modId="forge"
    mandatory=true
    versionRange="[42,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.customstartinggear]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3,1.19.4]"
    ordering="NONE"
    side="BOTH"
