modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT License"

[[mods]]
    modId="${mod_id}"
    displayName="Custom Starter Gear"
    version="${mod_version}"
	authors="${mod_authors}"
    description='''${mod_description}'''

[[dependencies.customstartinggear]]
    modId="forge"
    mandatory=true
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.customstartinggear]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
